[args]
database = "hashmap"
hasher = "sha256"
chunker = "ultra"

# uncomment for SeqCDC usage
# seq_mode = "increasing"

min = 4
avg = 8
max = 16

report_path = "report.csv"

[command.measure]
dataset_path = "Cargo.lock"
dataset_name = "a"
count = 1
cleanup = true