[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
itertools = "0.13"
chunkfs = { path = "../../chunkfs", features = ["chunkers", "hashers", "bench"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }